name: spoken
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.2.beta


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  flutter_dotenv: ^5.2.1
  dropdown_search: ^5.0.6
  firebase_core: ^2.27.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  mailer: ^6.0.1
  crypto: ^3.0.2
  shared_preferences: ^2.2.2




  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - .env

